name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README*'
      - '.git*'
      - '.vscode*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true

      - run: node --run build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  push-branch-compare:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: script
        env:
          BRANCH: compare
          DIR: .branch-compare
        run: |
          rm -rf $DIR
          git init -b $BRANCH $DIR
          cd $DIR
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          cp ../references/20260309.scratch3_ccw_data.e7237e1f.prettyprint.js ./scratch3_ccw_data.js
          git add .
          git commit -m "before"
          cp -f ../references/fix.scratch3_ccw_data.e7237e1f.prettyprint.js ./scratch3_ccw_data.js
          git add .
          git commit -m "fix"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin $BRANCH -f
